/**
 * Placeholder — auto-generated by Supabase CLI
 *
 * Run: pnpm types:gen   (or npm run types:gen)
 *
 * This will overwrite the file with strict types from live `abu-erp` schema.
 * Until then we expose a permissive shape so the rest of the app compiles.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; Relationships: [] }>;
    Views: Record<string, { Row: Record<string, unknown>; Relationships: [] }>;
    Functions: Record<string, unknown>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
